---

#############################################################
#  Retrieves a secret from a 1_secrets file
#
#  ansible-playbook ~/utils/decrypt_secret.yml \
#                   -i environments/george \
#                   -u maintuser \
#                   --private-key ~/.ssh/ansible.key \
#                   --vault-password-file ~/.ssh/vaultpwd \
#                   -e orchestrator=operations \
#                   -e secret_name=SECRET_NAME \
#                   -e debug_enabled=true
#
#                   Note: debug_enabled is optional
#
#############################################################

- name: Retrieve password from 1_secrets
  hosts: "{{ orchestrator }}"
  vars:
    env: "{{ inventory_dir | basename | default('george') }}"
    base_path: "{{ lookup('env', 'PWD') }}"
  tasks:
    - name: Fail if orchestrator not provided
      fail:
        msg: "Orchestrator (orchestrator) must be provided"
      when: orchestrator is not defined or orchestrator | length == 0
      no_log: true

    - name: Fail if secret name not provided
      fail:
        msg: "Secret name (secret_name) must be provided"
      when: secret_name is not defined or secret_name | length == 0
      no_log: true

    - name: Load secrets from 1_secrets file
      include_vars:
        file: "{{ base_path }}/environments/{{ env }}/group_vars/all/1_secrets"
        name: secrets
      when: env is defined

    - name: Debug available secret names in 1_secrets
      debug:
        msg: "Available secrets: {{ secrets.keys() | list }}"
      when: secrets is defined and debug_enabled | default(false) | bool

    - name: Fail if secret_name not found in 1_secrets
      fail:
        msg: "Secret '{{ secret_name }}' not found in 1_secrets"
      when: secrets[secret_name] is not defined
      no_log: true

    - name: Set password to variable
      set_fact:
        my_password: "{{ secrets[secret_name] | default('') }}"
      no_log: true

    - name: Debug the password variable
      debug:
        msg: "{{ secret_name }} value: {{ my_password }}"

